apiVersion: v1
appVersion: 0.12.3
description: Apache Druid (incubating) is a high performance analytics data store
  for event-driven data.
home: http://druid.io/
icon: http://druid.io/img/druid_nav.png
keywords:
- olap
- database
- analytics
maintainers:
- email: maciek@brynski.pl
  name: maver1ck
name: druid
sources:
- https://github.com/apache/incubator-druid
version: 0.1.1
