mysqlRootPassword: druidroot
mysqlUser: druid
mysqlPassword: druid
mysqlDatabase: druid
configurationFiles:
  mysql_collate.cnf: |-
    [mysqld]
    character-set-server=utf8
    collation-server=utf8_unicode_ci