apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ template "druid.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.indexer.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "druid.indexer.fullname" . }}
spec:
  serviceName: {{ template "druid.indexer.fullname" . }}
  replicas: {{ .Values.indexer.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "druid.name" . }}
      release: {{ .Release.Name }}
      component: {{ .Values.indexer.name }}
  template:
    metadata:
      labels:
        app: {{ template "druid.name" . }}
        component: {{ .Values.indexer.name }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/druid-sh-configmap.yaml") . | sha256sum }}
        {{- if .Values.indexer.podAnnotations }}
{{ toYaml .Values.indexer.podAnnotations | indent 8 }}
        {{- end }}
    spec:
      {{- if or .Values.indexer.antiAffinity .Values.indexer.nodeAffinity }}
      affinity:
      {{- end }}
      {{- if eq .Values.indexer.antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: "{{ template "druid.name" . }}"
                  release: "{{ .Release.Name }}"
                  component: "{{ .Values.indexer.name }}"
      {{- else if eq .Values.indexer.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: "{{ template "druid.name" . }}"
                  release: "{{ .Release.Name }}"
                  component: "{{ .Values.indexer.name }}"
      {{- end }}
      {{- with .Values.indexer.nodeAffinity }}
        nodeAffinity:
{{ toYaml . | indent 10 }}
      {{- end }}
{{- if .Values.indexer.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.indexer.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.indexer.tolerations }}
      tolerations:
{{ toYaml .Values.indexer.tolerations | indent 8 }}
{{- end }}
      volumes:
        - name: "druid-sh"
          configMap:
            name: "druid-sh"
            defaultMode: 0777
      containers:
      - name: druid
{{/*        args: [ "indexer" ]*/}}
        command: ["sleep", "300000"]
        env:
        {{- if .Values.zookeeper.enabled }}
        - name: ZOOKEEPER
          value: {{ .Release.Name }}-zookeeper-headless:2181
        {{- else }}
        - name: ZOOKEEPER
          value: {{ .Values.zkHosts }}
        {{- end }}
        {{- if .Values.mysql.enabled }}
        - name: DB_HOST
          value: {{ .Release.Name }}-mysql
        - name: DB_TYPE
          value: mysql
        - name: DB_USERNAME
          value: {{ .Values.mysql.mysqlUser }}
        - name: DB_PASSWORD
          value: {{ .Values.mysql.mysqlPassword }}
        - name: DB_DBNAME
          value: {{ .Values.mysql.mysqlDatabase }}
        - name: DB_PORT
          value: "3306"
        {{- end }}
        - name: JAVA_OPTS
          value: {{ .Values.indexer.javaOpts }}
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
{{/*        {{- range $key, $value := .Values.middle-manager }}*/}}
        resources:
{{ toYaml .Values.indexer.resources | indent 12 }}
{{/*        livenessProbe:*/}}
{{/*          initialDelaySeconds: 60*/}}
{{/*          httpGet:*/}}
{{/*            path: /status/health*/}}
{{/*            port: {{ .Values.indexer.port }}*/}}
{{/*        readinessProbe:*/}}
{{/*          initialDelaySeconds: 60*/}}
{{/*          httpGet:*/}}
{{/*            path: /status/health*/}}
{{/*            port: {{ .Values.indexer.port }}*/}}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: {{ .Values.indexer.port }}
          name: http
        volumeMounts:
        - mountPath: /var/druid/
          name: data
        - mountPath: /druid.sh
          subPath: druid.sh
          name: druid-sh
  {{- if not .Values.indexer.persistence.enabled }}
      volumes:
      - name: data
        emptyDir: {}
  {{- end }}
  updateStrategy:
    type: {{ .Values.indexer.updateStrategy.type }}
  {{- if .Values.indexer.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - {{ .Values.indexer.persistence.accessMode | quote }}
    {{- if .Values.indexer.persistence.storageClass }}
    {{- if (eq "-" .Values.indexer.persistence.storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .Values.indexer.persistence.storageClass }}"
    {{- end }}
    {{- end }}
      resources:
        requests:
          storage: "{{ .Values.indexer.persistence.size }}"
  {{ end }}
